version: '3'
services:
  sftp:
    image: atmoz/sftp
    volumes:
      - ./src/test/resources/input:/home/admin/input
      - ./src/test/resources/ssh_client_rsa_test_key.pub:/home/admin/.ssh/keys/id_rsa.pub:ro
    ports:
      - "2222:22"
    command: admin::1001